# Generated by Django 3.0.1 on 2019-12-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('credit_rate', models.IntegerField()),
                ('min_credit_time', models.IntegerField()),
                ('max_credit_time', models.IntegerField()),
                ('credit_sum', models.DecimalField(decimal_places=2, max_digits=8)),
                ('early_repayment', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=48)),
            ],
        ),
    ]
