# Generated by Django 3.0.1 on 2019-12-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditproduct',
            name='slug',
        ),
    ]
