# Generated by Django 3.0.1 on 2019-12-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_product', '0002_remove_creditproduct_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditproduct',
            old_name='credit_sum',
            new_name='max_credit_sum',
        ),
        migrations.AddField(
            model_name='creditproduct',
            name='min_credit_sum',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8),
            preserve_default=False,
        ),
    ]
